-- 将该建表 SQL 语句，添加到 yudao-module-training-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "training_classes" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar NOT NULL,
    "store_id" bigint,
    "coach_id" varchar,
    "start_date" varchar,
    "end_date" varchar,
    "day" varchar,
    "start_time" varchar,
    "end_time" varchar,
    "avatar" varchar,
    "type" varchar,
    "extend" varchar,
    "status" varchar NOT NULL,
    "remark" varchar,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL,
    PRIMARY KEY ("id")
) COMMENT '班级信息表';

-- 将该删表 SQL 语句，添加到 yudao-module-training-biz 模块的 test/resources/sql/clean.sql 文件里
DELETE FROM "training_classes";
