-- 将该建表 SQL 语句，添加到 yudao-module-system-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "system_class_type" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar NOT NULL,
    "type" varchar NOT NULL,
    "group" varchar NOT NULL,
    "structure" varchar,
    "status" varchar NOT NULL,
    "remark" varchar,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "deleted_time" varchar,
    PRIMARY KEY ("id")
) COMMENT '类型表';

-- 将该删表 SQL 语句，添加到 yudao-module-system-biz 模块的 test/resources/sql/clean.sql 文件里
DELETE FROM "system_class_type";
