-- 将该建表 SQL 语句，添加到 yudao-module-training-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "training_store" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar NOT NULL,
    "mobile" varchar,
    "address" varchar NOT NULL,
    "longitude" varchar NOT NULL,
    "latitude" varchar NOT NULL,
    "logo" varchar,
    "images" varchar,
    "introduce" varchar,
    "notice" varchar,
    "business_hours" varchar,
    "sort" int NOT NULL,
    "status" bit NOT NULL,
    "recommend" bit NOT NULL,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL,
    PRIMARY KEY ("id")
) COMMENT '门店表';

-- 将该删表 SQL 语句，添加到 yudao-module-training-biz 模块的 test/resources/sql/clean.sql 文件里
DELETE FROM "training_store";
